feat: add importer for Digital Credit Union
redstreet/beancount_reds_importers pull request #89
Opened 2023-12-20 23:41 UTC by hlieberman

This adds a CSV importer for Digital Federal Credit Union (DCU), the 18th largest credit union in the United States (by total assets under management). Unfortunately, DCU doesn't offer OFX exports, so this is the best we can do.

2023-12-21 00:09 UTC, redstreet commented on beancount_reds_importers/importers/dcu/__init__.py
> +"""DCU (Digital Federal Credit Union) ofx importer for beancount."""
ofx -> csv

2023-12-21 00:10 UTC, hlieberman commented on beancount_reds_importers/importers/dcu/__init__.py
> +"""DCU (Digital Federal Credit Union) ofx importer for beancount."""
Derp.  One sec, pushing a fix now.

2023-12-21 00:17 UTC, redstreet commented
Nice, thanks! For csv importers, it's far more important to have unit tests (compared to ofx), so would you mind adding at least a couple lines? It's simple: `beancount_reds_importers/importers/schwab/tests/schwab_csv_checking` is a good example.

2023-12-21 00:26 UTC, hlieberman commented
Yeah, no problem.  Would you mind if I pulled in another dependency, at least as dev dep? (I try, whenever possible, to add hypothesis tests if I'm going to write unit tests -- in addition to a static test.)

2023-12-21 00:41 UTC, redstreet commented
Sure, dev dependencies are fine.

2023-12-22 03:25 UTC, hlieberman commented
@redstreet, I ended up not using hypothesis after all.  I wrote up a test, but it really is testing beancount more than it's testing the importer, since it's making sure a series of random transactions that balance before import, balance after import.

2023-12-22 06:05 UTC, redstreet commented
Makes sense, and sounds good. If you don't mind addressing the comment above about `'USD'`, I can merge this in.

2023-12-22 14:36 UTC, hlieberman commented
> the comment above about `'USD'`

I'm sorry, I must be blind; I don't see anything about USD above.  The only comment I see on the code is the ofx => csv one.

2023-12-22 20:01 UTC, redstreet requested changes

2023-12-22 20:02 UTC, redstreet commented
> I'm sorry, I must be blind; I don't see anything about USD above.  The only comment I see on the code is the ofx => csv one.

Drat, completely my bad, sorry! Github requires separately hitting a "submit review" as a second step when adding a comment as a part of a review (as opposed to adding a freestanding comment). This is non-obvious and not at all the first time I've been tripped up by it. It should be visible now.

2023-12-22 20:15 UTC, hlieberman commented on beancount_reds_importers/importers/dcu/__init__.py
> +            self.currency = "USD"
No problem; change pushed.

2023-12-22 20:16 UTC, hlieberman commented
> Drat, completely my bad, sorry! Github requires separately hitting a "submit review" as a second step when adding a comment as a part of a review (as opposed to adding a freestanding comment).
Ah yes, I've been bitten by this one myself a couple of times.  Change made!

2023-12-22 20:38 UTC, redstreet commented
Awesome, thank you!

2023-12-22 20:38 UTC, merged

2023-12-22 20:39 UTC, redstreet commented
MErged